default_velocty_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0


joint_limits: # overrides values from the urdf file
  gripper_joint:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 4.0
    has_jerk_limits: false
  gripper_joint_sub:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 4.0
    has_jerk_limits: false
  joint1:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 4.0
    has_jerk_limits: false
  joint2:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 3.0
    has_jerk_limits: false
  joint3:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 3.0
    has_jerk_limits: false
  joint4:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 3.0
    has_jerk_limits: false
