
moveit_controller_manager: moveit_open_x_manager/MoveItSimpleControllerManager
controller_names:
  - arm_controller
  - gripper_controller

arm_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints: 
    - joint1
    - joint2
    - joint3
    - joint4

gripper_controller:
type: GripperCommand
joints:
  - gripper
  - gripper_sub
  action_ns: gripper_cmd
  default: true

