classes:
  - red:
      channels:
        hue:
          lower_bound: 0
          upper_bound: 10
        saturation:
          lower_bound: 50
          upper_bound: 100
        value:
          lower_bound: 20
          upper_bound: 80
  - blue:
      channels:
        hue:
          lower_bound: 220
          upper_bound: 240
        saturation:
          lower_bound: 60
          upper_bound: 100
        value:
          lower_bound: 20
          upper_bound: 50
  - green:
      channels:
        hue:
          lower_bound: 110
          upper_bound: 135
        saturation:
          lower_bound: 50
          upper_bound: 100
        value:
          lower_bound: 20
          upper_bound: 50
