classes:
  - red:
      channels:
        hue:
          lower_bound: 0
          upper_bound: 10
        saturation:
          lower_bound: 230
          upper_bound: 255
        value:
          lower_bound: 20
          upper_bound: 255
  - blue:
      channels:
        hue:
          lower_bound: 100
          upper_bound: 140
        saturation:
          lower_bound: 00
          upper_bound: 256
        value:
          lower_bound: 80
          upper_bound: 120
  - green:
      channels:
        hue:
          lower_bound: 110
          upper_bound: 135
        saturation:
          lower_bound: 50
          upper_bound: 100
        value:
          lower_bound: 20
          upper_bound: 50
